
# MySql
spring:
  application:
    name: CRUD_Practice
  profiles:
    include: secret
  # Hibernate JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
